komponentkeeper/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static
from komponentkeeperapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('komponentkeeperapp.urls')),
] 

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

komponentkeeperapp/urls.py
# from django.conf.urls import url, include
from django.urls import path, include
from django.conf.urls import url
from .views import *

app_name = 'komponentkeeperapp'

urlpatterns = [
    path('accounts/login', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # * Here is the edit   
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    
    path('home', home, name='home'),
    path('components/', components_list, name='components'),
    # url(r'^components/(?P<pk>.*)', components_list, name='components'),

    path('components/<int:component_id>/', component_details, name='component'),
    path('components/form', upload_component, name='upload_component'),
    path('components/<int:component_id>/form', edit_component_form, name='edit_component_form'),

    path('success', success, name='success'), 
    path('edit_success', success, name='edit_success'), 
    path('fail', fail, name='fail'), 

    # Snippet related routes
    path('snippets/<int:component_id>/form', snippet_form, name='snippet_form'), # * Added <int:component_id>    
    path('snippets/<int:component_id>', snippets_list, name='snippets'), 
    path('snippets/<int:snippet_id>/form', edit_snippet_form, name='edit_snippet_form'),
    path('snippets/<int:snippet_id>/editSnippet', edit_snippet_form, name='edit_snippet_form'),
    path('snippets/<int:snippet_id>/', snippet_details, name='snippet'),
    
]

komponentkeeperapp/models/code_snippets.py
from django.db import models
from .components import Component
from .creators import Creator
class CodeSnippet(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        creator: This will contain user id's to see which user created the snippet
        snippet_language: This will contain a string describing the language of the snipped
        code_snippet: This will contain a code snippet for a component
        description: This will contain any notes about the snippet
    '''
    component = models.ForeignKey("Component", on_delete=models.SET_NULL, null=True)
    creator = models.ForeignKey('Creator',  on_delete=models.SET_NULL, null=True)
    snippet_language = models.CharField(max_length=50, default=None, null=True)
    code_snippet = models.TextField(max_length=500, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    
    class Meta:
        verbose_name = ("CodeSnippet")
        verbose_name_plural = ("CodeSnippets")

    # def get_absolute_url(self):
    #     return reverse("CodeSnippet_details", kwargs={"pk": self.pk})
    
    # def __str__(self):
    #     return f'creator :: {self.creator}'

komponentkeeperapp/models/components.py
from django.db import models
from .creators import Creator

class Component(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        creator: This will contain user id's to see which user created it
        name: this will contain the name of the component
        image: This property will contain a path to an image file
        description: this property will contain a description of the component
    '''

    creator = models.ForeignKey("Creator",  on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, null=True, default=None)
    # upload_to tells the model where to store the image, by default images/ will go to the media directory
    image = models.ImageField(upload_to='images/', null=True)
    description = models.CharField( max_length=200, null=True, default=None)

    class Meta:
        verbose_name = ("Component")
        verbose_name_plural = ("Components")

    def get_absolute_url(self):
        return reverse("component_detail", kwargs={"pk": self.pk})

komponentkeeperapp/models/creators.py
from django.db import models
from django.contrib.auth.models import User

class Creator(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        user: This will contain user id's to see which user created it
        username: This will contain the user's username
        first_name: This will contain the user's first name
        last_name: This will contain the user's last name
        email: This will contain the user's email
        role: This will contain the user's role
    '''

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=25, default=None, null=True)
    first_name = models.CharField(max_length=50, default=None, null=True)
    last_name = models.CharField(max_length=50, default=None, null=True)
    email = models.CharField(max_length=75, default=None, null=True)
    role = models.CharField(max_length=15, default=None, null=True)
    
    class Meta:
        verbose_name = ("Creator")
        verbose_name_plural = ("Creators")

    def get_absolute_url(self):
        return reverse("Creator", kwargs={"pk": self.pk})

komponentkeeperapp/models/m_code_snippets.py
from django.db import models

class CodeSnippet(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        user_id: This will contain user id's to see which user created the snippet
        snippet_language: This will contain a string describing the language of the snipped
        code_snippet: This will contain a code snippet for a component
        description: This will contain any notes about the snippet
    '''

    user_id = models.models.ForeignKey("users",  on_delete=models.CASCADE)
    snippet_language = models.CharField(max_length=50, default=None, null=True)
    code_snippet = models.CharField( max_length=500)
    description = models.CharField(max_length=200)
    
    class Meta:
        verbose_name = ("CodeSnippet")
        verbose_name_plural = ("CodeSnippets")

    def get_absolute_url(self):
        return reverse("CodeSnippet_details", kwargs={"pk": self.pk})

komponentkeeperapp/models/m_components.py
from django.db import models

class Component(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        user_id: This will contain user id's to see which user created it
        image: This property will contain a path to an image file
        description: this property will contain a description of the component
    '''

    user_id = models.models.ForeignKey("users",  on_delete=models.CASCADE)
    image = models.CharField( max_length=150, null=True, default=None)
    description = models.CharField( max_length=200, null=True, default=None)

    class Meta:
        verbose_name = ("Component")
        verbose_name_plural = ("Components")

    def get_absolute_url(self):
        return reverse("component_detail", kwargs={"pk": self.pk})

komponentkeeperapp/models/m_users.py
from django.db import models

class User(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        user_id: This will contain user id's to see which user created it
        username: This will contain the user's username
        first_name: This will contain the user's first name
        last_name: This will contain the user's last name
        email: This will contain the user's email
        role: This will contain the user's role
    '''

    user_id = models.models.ForeignKey("users",  on_delete=models.CASCADE)
    username = models.CharField(max_length=25, default=None, null=True)
    first_name = models.CharField(max_length=50, default=None, null=True)
    last_name = models.CharField(max_length=50, default=None, null=True)
    email = models.CharField(max_length=75, default=None, null=True)
    role = models.IntegerField()
    
    class Meta:
        verbose_name = ("Computer")
        verbose_name_plural = ("Computers")

    def get_absolute_url(self):
        return reverse("Computer_detail", kwargs={"pk": self.pk})

komponentkeeperapp/forms.py
from django.forms import ModelForm
from .models.components import Component

class AddImageForm(ModelForm):
    class Meta:
        model = Component
        exclude = ['creator']
        # fields = ['name', 'image', 'description']

class EditComponentForm(ModelForm):
    class Meta:
        model = Component
        exclude = ['creator']
        # fields = ['name', 'image', 'description']

komponentkeeperapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

komponentkeeperapp/templates/components/add_component_form.html
{% load static %}
<form method = "post" enctype="multipart/form-data"> 
    {% csrf_token %} 
    {{ form.as_p}} 
    <button type="submit">Upload</button> 
</form> 

komponentkeeperapp/templates/components/details.html
{% extends 'shared/base.html' %}
{% load static %}
{# fields to display component. name, image, description, creator. first_name, last_name#}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/components/components.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/components/snippets.css' %}">
{% endblock %}

{% block content %}

    <a id="component-detail-back-button" class="animated bounceIn" href="{% url 'komponentkeeperapp:components' %}"> < </a>
    
        <div class="component-detail-container">
        <div class="component-detail-row">
            <div id="component-detail-col-one">
                <h3 id="detail-view-main-heading">{{component.name}}</h3>
                <div class="detail-img-container">
                    <img src="{{component.image.url}}" alt="A component" class="detail-component-img">
                </div>
            </div>
            <div id="component-detail-col-two">
                <h4 class="detail-heading">Description</h4>
                <p class="detail-component-description">
                    {{component.description}}
                </p>
                <h4 class="detail-heading">Created By</h4>
                <p class="created-by">{{component.creator.first_name}} {{component.creator.last_name}}</p>
            </div>
        </div>
        </div>
        
        <div class="controls-container">
            <div class="controls-row">
                <div class="controls-col">
                    <!-- *Add snippet button -->
                    <form action="{% url 'komponentkeeperapp:snippet_form' component.id %}" method="get">
                        <input type="hidden" value="{{component.id}}">
                        <button class="details-button" type="submit">Add Snippet</button>
                    </form>
                </div>
                <div class="controls-col">
                    <!-- * DELETE Component Button -->
                    <form action="{% url 'komponentkeeperapp:component' component.id %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="actual_method" value="DELETE">
                        <button class="details-button">Delete Komponent</button>
                    </form>
                </div>
                <div class="controls-col">
                    <!-- * EDIT Component Button -->
                    <form action="{% url 'komponentkeeperapp:edit_component_form' component.id %}" method="GET">
                        {% csrf_token %}
                        <button class="details-button">Edit Komponent</button>
                    </form>
                </div>
                </div>
            </div>


            {% for s in snippet %}
                {% if s.snippet_language is None %}
                <div class="no-snippet"></div>
                {% else %}
                    <div class="snippet-card">
                        <h3 class="snippet-heading">Snippet Language</h3>
                        <p class="snippet-language">{{s.snippet_language}}</p>
                            <pre class="prettyprint lang-{{s.snippet_language|lower}}">
                                {{s.code_snippet}}
                            </pre>
                            <p class="snippet-desc">{{s.description}}</p>
                    </div>


                    <div class="snippet-controls-container">
                        <div class="controls-row">
                            <div class="controls-col">
                                <form action="{% url 'komponentkeeperapp:edit_snippet_form' s.id %}" >
                                    {% csrf_token %}
                                    <input type="hidden" >
                                    <button id="scroll-to-position" class="details-button" type="submit">EDIT SNIPPET</button>
                                </form>
                            </div>

                            <div class="controls-col">
                                <form action="{% url 'komponentkeeperapp:snippet' s.id %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="actual_method" value="DELETE">
                                    <button class="details-button">Delete Snippet</button>
                                </form>
                            </div>

                        </div>
                    </div>
                {% endif %}
            {% endfor %}
    
    </div>

   


    {% endblock content %}

komponentkeeperapp/templates/components/edit_component_form.html
{% load static %}

<!DOCTYPE html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8"> 
    <title>Edit Component</title> 
</head> 
<body> 
    <form method ="post" enctype="multipart/form-data"> 
        {{ form.errors }}
        {{ form.non_field_errors }}
        {% csrf_token %} 
        {{ form.as_p}} 
        <button type="submit">Submit Changes</button> 
    </form> 
</body> 
</html> 

komponentkeeperapp/templates/components/list.html
{% extends 'shared/base.html' %}
{% load static %}
{# fields to display component. name, image, description, creator. first_name, last_name#}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/components/components.css' %}">
{% endblock %}

{% block content %}
    <h1 class="main-heading">Components</h1>
    <p class="heading-description">
        View your stored Komponents below, or add a new one on the bottom right corner.
    </p>
    <p class="heading-description">
        Here you can view the details of a Komponent, then edit it's values, or delete it.
    </p>

    <a id="add-component-button" class="animated bounceIn" href="{% url 'komponentkeeperapp:upload_component' %}">+</a>

    <div class="component-card-container">
    {% for component in user_components %}
        <div class="component-card animated bounceInUp slower">
            <div class="list-card-row">
                <div class="list-card-col">
                    <h3 class="card-heading">Komponent Name</h3>
                    <p class="component-card-name">{{component.name}}</p>
                    <div class="img-container">
                        <img src="{{component.image.url}}" alt="A component" class="component-img">
                    </div>
                </div>

                <div class="list-card-col">
                    <h4 class="list-created-by">Created By</h4>
                    <p class="list-created-by">{{component.creator.first_name}}</p>
                </div>
            </div>
            
            <!-- TODO Add animations to buttons -->
            <form action="{% url 'komponentkeeperapp:component' component.id %}" method="get">
                <button class="component-details-button" type="submit">View Details</button>
            </form>
            <!-- <a href="{% url 'komponentkeeperapp:component' component.id %}">View Details</a> -->
        </div>
        {% endfor %}
    </div>

    {% endblock content %}
    {% block scripts %}
    <script src="{% static 'js/animations.js' %}"></script>
    {% endblock scripts %}