komponentkeeper/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static
from komponentkeeperapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('komponentkeeperapp.urls')),
] 

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

komponentkeeperapp/urls.py
# from django.conf.urls import url, include
from django.urls import path, include
from django.conf.urls import url
from .views import *

app_name = 'komponentkeeperapp'

urlpatterns = [
    path('accounts/login', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # * Here is the edit   
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    
    path('home', home, name='home'),
    path('components/', components_list, name='components'),
    # url(r'^components/(?P<pk>.*)', components_list, name='components'),

    path('components/<int:component_id>/', component_details, name='component'),
    path('components/form', upload_component, name='upload_component'),
    path('components/<int:component_id>/form', edit_component_form, name='edit_component_form'),

    path('success', success, name='success'), 
    path('edit_success', success, name='edit_success'), 
    path('fail', fail, name='fail'), 

    # Snippet related routes
    path('snippets/<int:component_id>/form', snippet_form, name='snippet_form'), # * Added <int:component_id>    
    path('snippets/<int:component_id>', snippets_list, name='snippets'), 
    path('snippets/<int:snippet_id>/form', edit_snippet_form, name='edit_snippet_form'),
    path('snippets/<int:snippet_id>/editSnippet', edit_snippet_form, name='edit_snippet_form'),
    path('snippets/<int:snippet_id>/', snippet_details, name='snippet'),
    
]

komponentkeeperapp/models/code_snippets.py
from django.db import models
from .components import Component
from .creators import Creator
class CodeSnippet(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        creator: This will contain user id's to see which user created the snippet
        snippet_language: This will contain a string describing the language of the snipped
        code_snippet: This will contain a code snippet for a component
        description: This will contain any notes about the snippet
    '''
    component = models.ForeignKey("Component", on_delete=models.SET_NULL, null=True)
    creator = models.ForeignKey('Creator',  on_delete=models.SET_NULL, null=True)
    snippet_language = models.CharField(max_length=50, default=None, null=True)
    code_snippet = models.TextField(max_length=500, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    
    class Meta:
        verbose_name = ("CodeSnippet")
        verbose_name_plural = ("CodeSnippets")

    # def get_absolute_url(self):
    #     return reverse("CodeSnippet_details", kwargs={"pk": self.pk})
    
    # def __str__(self):
    #     return f'creator :: {self.creator}'

komponentkeeperapp/models/components.py
from django.db import models
from .creators import Creator

class Component(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        creator: This will contain user id's to see which user created it
        name: this will contain the name of the component
        image: This property will contain a path to an image file
        description: this property will contain a description of the component
    '''

    creator = models.ForeignKey("Creator",  on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, null=True, default=None)
    # upload_to tells the model where to store the image, by default images/ will go to the media directory
    image = models.ImageField(upload_to='images/', null=True)
    description = models.CharField( max_length=200, null=True, default=None)

    class Meta:
        verbose_name = ("Component")
        verbose_name_plural = ("Components")

    def get_absolute_url(self):
        return reverse("component_detail", kwargs={"pk": self.pk})

komponentkeeperapp/models/creators.py
from django.db import models
from django.contrib.auth.models import User

class Creator(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        user: This will contain user id's to see which user created it
        username: This will contain the user's username
        first_name: This will contain the user's first name
        last_name: This will contain the user's last name
        email: This will contain the user's email
        role: This will contain the user's role
    '''

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=25, default=None, null=True)
    first_name = models.CharField(max_length=50, default=None, null=True)
    last_name = models.CharField(max_length=50, default=None, null=True)
    email = models.CharField(max_length=75, default=None, null=True)
    role = models.CharField(max_length=15, default=None, null=True)
    
    class Meta:
        verbose_name = ("Creator")
        verbose_name_plural = ("Creators")

    def get_absolute_url(self):
        return reverse("Creator", kwargs={"pk": self.pk})

komponentkeeperapp/models/m_code_snippets.py
from django.db import models

class CodeSnippet(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        user_id: This will contain user id's to see which user created the snippet
        snippet_language: This will contain a string describing the language of the snipped
        code_snippet: This will contain a code snippet for a component
        description: This will contain any notes about the snippet
    '''

    user_id = models.models.ForeignKey("users",  on_delete=models.CASCADE)
    snippet_language = models.CharField(max_length=50, default=None, null=True)
    code_snippet = models.CharField( max_length=500)
    description = models.CharField(max_length=200)
    
    class Meta:
        verbose_name = ("CodeSnippet")
        verbose_name_plural = ("CodeSnippets")

    def get_absolute_url(self):
        return reverse("CodeSnippet_details", kwargs={"pk": self.pk})

komponentkeeperapp/models/m_components.py
from django.db import models

class Component(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        user_id: This will contain user id's to see which user created it
        image: This property will contain a path to an image file
        description: this property will contain a description of the component
    '''

    user_id = models.models.ForeignKey("users",  on_delete=models.CASCADE)
    image = models.CharField( max_length=150, null=True, default=None)
    description = models.CharField( max_length=200, null=True, default=None)

    class Meta:
        verbose_name = ("Component")
        verbose_name_plural = ("Components")

    def get_absolute_url(self):
        return reverse("component_detail", kwargs={"pk": self.pk})

komponentkeeperapp/models/m_users.py
from django.db import models

class User(models.Model):
    '''
    description: This class creates a component and its associated data
    author: Jesie Oldenburg
    properties:
        user_id: This will contain user id's to see which user created it
        username: This will contain the user's username
        first_name: This will contain the user's first name
        last_name: This will contain the user's last name
        email: This will contain the user's email
        role: This will contain the user's role
    '''

    user_id = models.models.ForeignKey("users",  on_delete=models.CASCADE)
    username = models.CharField(max_length=25, default=None, null=True)
    first_name = models.CharField(max_length=50, default=None, null=True)
    last_name = models.CharField(max_length=50, default=None, null=True)
    email = models.CharField(max_length=75, default=None, null=True)
    role = models.IntegerField()
    
    class Meta:
        verbose_name = ("Computer")
        verbose_name_plural = ("Computers")

    def get_absolute_url(self):
        return reverse("Computer_detail", kwargs={"pk": self.pk})

komponentkeeperapp/forms.py
from django.forms import ModelForm
from .models.components import Component

class AddImageForm(ModelForm):
    class Meta:
        model = Component
        exclude = ['creator']
        # fields = ['name', 'image', 'description']

class EditComponentForm(ModelForm):
    class Meta:
        model = Component
        exclude = ['creator']
        # fields = ['name', 'image', 'description']

komponentkeeperapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

komponentkeeperapp/templates/code_snippets/details.html
{% extends 'shared/base.html' %}
{# fields to display code_snippet. snippet, creator, snippet_language, description :: creator. first_name, last_name #}

{% load static %}

{% block content %}
    <h1>Code Snippets</h1>

    <div class="container">
        <div class="snippet-card">
            <h3 class="card-heading">{{snippet.snippet_language}}</h3>
            <div class="snippet-container">
                <p>{{snippet.code_snippet}}</p>
            </div>
            <p class="created-by">{{snippet.creator.first_name}} {{snippet.creator.last_name}}</p>
            <p class="snippet-description">{{snippet.description}}</p>
        </div>
    </div>

    <form action="{% url 'komponentkeeperapp:edit_snippet_form' snippet.id %}" method="GET">
        {% csrf_token %}
        <button>Edit</button>
    </form>

    <form action="{% url 'komponentkeeperapp:snippet' snippet.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="actual_method" value="DELETE">
        <button>Delete</button>
    </form> 


    
    {% endblock content %}

komponentkeeperapp/templates/code_snippets/editSnippet.html
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/forms.css' %}">
{% endblock %}  

    <h1 class="form-heading">Edit Current Snippet</h1>

    <form action="{% url 'komponentkeeperapp:snippet' snippet.id %}" method="post">
        
      {% csrf_token %}
            
      <div class="form-field-container">
          <div class="form-row">
              <fieldset>
                  <div class="label-separation-row">
                      <label class="form-labels" for="snippet-language">Edit The Snippet Language</label>
                  </div>
                  <div class="label-separation-row">
                      <input id="snippet-language" type="text" name="snippet-language" value="{{ snippet.snippet_language }}">
                  </div>
              </fieldset> 
          </div>
      
          <div class="form-row">
              <fieldset>
                <div class="label-separation-row">
                    <label class="form-labels" for="description">Edit Your Description</label>
                </div>
                <div class="label-separation-row">
                    <textarea id="description" rows="5" cols="35" name="description" >{{ snippet.description }}</textarea>
                </div>
              </fieldset>
          </div>

          <div class="form-row">
              <fieldset>
                <div class="label-separation-row">
                    <label class="form-labels" for="snippet-input">Edit Your Existing Snippet</label>
                </div>
                <div class="label-separation-row">
                    <textarea id="snippet-input" rows="30" cols="75" name="snippet-input" > {{ snippet.code_snippet }} </textarea>
                </div>
              </fieldset>
          </div>
    </div>
      <input type="hidden" name="actual_method" value="PUT">
      <input class="form-submit-button" type="submit" value="Update" />
          
    </form>

komponentkeeperapp/templates/code_snippets/form.html
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/forms.css' %}">
{% endblock %}  
<h1 class="form-heading">Add a New Snippet</h1>
    {% if s.id is not None %}
    <form action="{% url 'komponentkeeperapp:snippet' s.id%}" method="post">
    {% else %}
    <form action="{% url 'komponentkeeperapp:snippets' component.id %}" method="post">
    {% endif %}
        <div class="form-field-container">
            {% csrf_token %}
            <div class="form-row">
                <fieldset>
                    <div class="label-separation-row">
                        <label class="form-labels" for="snippet-language">Snippet Language</label>
                    </div>
                    <div class="label-separation-row">
                        <input id="snippet-language" type="text" name="snippet-language" value="{{ snippet.snippet_language }}">
                    </div>
                </fieldset> 
            </div>
      
            <div class="form-row">
                <fieldset>
                  <div class="label-separation-row">
                      <label class="form-labels" for="description">Leave a small description</label>
                  </div>
                  <div class="label-separation-row">
                      <textarea id="description" rows="5" cols="35" name="description" >{{ snippet.description }}</textarea>
                  </div>
                </fieldset>
            </div>
              
            <div class="form-row">
                <fieldset>
                  <div class="label-separation-row">
                      <label class="form-labels" for="snippet-input">Paste Your Snippet Here</label>
                  </div>
                  <div class="label-separation-row">
                      <textarea id="snippet-input" rows="30" cols="75" name="snippet-input" > {{ snippet.code_snippet }} </textarea>
                  </div>
                </fieldset>
            </div>
        </div>
        


      
      {% if snippet.id is not None %}
      <input type="hidden" name="actual_method" value="PUT">
      <input class="form-submit-button" type="submit" value="Update" />
      {% else %}
      <input type="hidden" name="actual_method" value="PUT">
      <input class="form-submit-button" type="submit" value="Create" />
      {% endif %}
          
    </form>

komponentkeeperapp/templates/code_snippets/list.html
{% extends 'shared/base.html' %}
{# fields to display code_snippet. snippet, creator, snippet_language, description :: creator. first_name, last_name #}
{% load static %}
{% block content %}
    <h1>Code Snippets</h1>
    {% for snippet in all_snippets %}
    <div class="container">
        <div class="snippet-card">
            <h3 class="card-heading">{{snippet.snippet_language}}</h3>
            <div class="snippet-container">
                <p>{{snippet.code_snippet}}</p>
            </div>
            <p class="created-by">{{snippet.creator.first_name}} {{snippet.creator.last_name}}</p>
            <p class="snippet-description">{{snippet.description}}</p>
            
        </div>
    </div>
    {% endfor %}
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    {% endblock content %}